### ISSUE TITLE
integration test keeps failing because of `too many open files`

### ISSUE THREAD

**Issue by sio4** [gobuffalo/cli#116]
### Description

Integration test keeps failing with the error `too many open files` on my Ubuntu system (but it seems like Github Action provides better computing options :-) The failing test is related to `buffalo fix` such as `TestFix_v0_18_0/web`. Error message is interesting:

```
time="2022-03-11T12:27:25+09:00" level=error msg="Error: open /tmp/buffalo-integration-test-3428336135/web/node_modules/@fortawesome/fontawesome-free/svgs/solid/flask.svg: too many open files"
```

It seems like the `fix` function opens lots of files at once, also I don't think files under `node_modules` are targets of buffalo version upgrade fixing.

### Steps to Reproduce the Problem

  1. `go test -v -p 1 -tags "sqlite,integration" -run TestFix_v0_18_0/web -cover ./...`

### Expected Behavior

- The tests should be done without error on an ordinary system.
- Fix should not touch files under `node_modules` or similar directories.

### Actual Behavior

- It seems like the `fix` trying to open all files under the application tree, including `node_modules`, and failed with `too many open files` error.

**Comment by sio4** [comment]
It seems like the issue is on gobuffalo/genny, and I am working on it.

**Comment by sio4** [comment]
I found that the `fix` command starts with building a filesystem for generator/runner. While scanning the target directory, it opens every file under the root instead of just building a file information table, regardless of they need to be open or not.

https://github.com/gobuffalo/cli/blob/e63f7686eb0155284ca86d9fab6b4a4f3510cbe0/internal/genny/fix/fix.go#L68-L70

Line 68 of the above code calls `g.FS()`, then

https://github.com/gobuffalo/genny/blob/774b5b9d23bc5f3a162fc476de452e77a64ae863/generator.go#L92-L96

in the function, Line 92 opens all files.

This is too bad from both a resource perspective and a security perspective, but it could be a big surgery if we try to fix this while keeping it compatible. 

Just for now, I would like to create a workaround implementation called SelectiveFS in `genny` that has support excluding and including options. (will PR soon) After that, I am going to fix cli to use that SelectiveFS approach.

**Comment by paganotoni** [comment]
@sio4 was this one solved with recent merges?

**Comment by sio4** [comment]
Oh, yes. This was resolved. I forgot closing it.
