### ISSUE TITLE
Unable to install plugins on M1 - issue with golang 1.18 - golang.org/x/sys/unix

### ISSUE THREAD

**Issue by rvarun11** [gobuffalo/cli#157]
### Description 
Inability to install buffalo plugins via the `buffalo plugins install` command.

### Steps to reproduce
Try installing any plugin via the cli. For eg.:
1. `buffalo plugins install github.com/gobuffalo/buffalo-auth`
2. `buffalo plugins install github.com/gobuffalo/buffalo-goth`

### Expected Behaviour
Installs the respective plugin. 

### Actual Behaviour
Getting the following error message:

```
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200124204421-9fbb57f87de9/unix/zsyscall_darwin_arm64.go:121:3: too many errors
Usage:
  buffalo plugins install [flags]

Flags:
  -d, --dry-run   dry run
  -h, --help      help for install
      --vendor    will install plugin binaries into ./plugins [WINDOWS not currently supported]
  -v, --verbose   turn on verbose logging

ERRO[0000] Error: exit status 2            
```

### System Information
Installed plugin support using: `go get -u -v github.com/gobuffalo/buffalo-plugins`
Buffalo Version: 0.18.5
Go Version: 1.18.2 darwin/arm64

### Dirty Fix

The fix as per [offical golang docs](https://pkg.go.dev/golang.org/x/sys#section-readme) is to run `go get -u golang.org/x/sys` to upgrade _golang.org/x/sys_ however that isn't working for the Buffalo CLI because it seems to be relying on the old version of _golang.org/x/sys_ (Version: @v0.0.0-20200124204421-9fbb57f87de9) as seen from the above error message. As a quick fix I just  renamed the `sys@v0.0.0-20200124204421-9fbb57f87de9` folder to `sys@v0.0.0-20220520151302-bc2c85ada10a` (the latest version) and it worked.

**Comment by rvarun11** [comment]
closing as duplicate of https://github.com/gobuffalo/cli/issues/157

**Comment by EwanValentine** [comment]
I'm also seeing this, was there a solution to this in the end?

**Comment by rvarun11** [comment]
@EwanValentine I continued working with the dirty fix so far.
