### ISSUE TITLE
generated ci-provider configs are outdated

### ISSUE THREAD

**Issue by sio4** [gobuffalo/cli#202]
Generated ci-provider configurations still use the old version of `go get` command for installing buffalo, and the database version or others are also somewhat outdated.

Also, I am not sure if we need to support them all since supporting them all could be heavy for the team and actually, the configuration could not be the same for all users so the cost and benefit could be unbalanced.

> actually, it will not work. it should be replaced with `go install github.com/gobuffalo/cli/cmd/buffalo@latest` (and `go mod download` may not be required). I know you added this line copied from the others which is not maintained for a while :-(

_Originally posted by @sio4 in https://github.com/gobuffalo/cli/pull/197#discussion_r924414247_

**Comment by VictorBersy** [comment]
Maybe support only Gitlab and Github, so users have something working out-of-the-box, as they are probably already using one or the other?

**Comment by paganotoni** [comment]
I think I agree with @VictorBersy. @sio4 if you approve only having Github and Gitlab I am up to implement this change.

**Comment by sio4** [comment]
I agree! that could be enough for scaffolding.
