### ISSUE TITLE
resource generation with partial undetected

### ISSUE THREAD

**Issue by adamtang79** [gobuffalo/cli#208]
### Description

Partial of plush is not working.

### Steps to Reproduce the Problem

  Please describe in painful detail what you did (so others can play along with you) to get to this point. This includes things like the exact command(s) you used, or the `curl` command you used, that sort of thing.

  1. execute "buffalo g r invitations token:string expired_at:time.Time recalled:bool total_login:int"
  2. execute "buffalo dev"
  3. browse "http://localhost:3000/invitations/"
  4. click "Create New Invitation"

### Expected Behavior

Able to create a new invitation.

### Actual Behavior

at "http://localhost:3000/invitations/new/"

500 - ERROR!

Error Trace: "invitations/new.plush.html: line 6: could not call formFor function: could not call partial function: could not find template invitations\_form.html"

Context: "T: %!s(i18n.TranslateFunc=0xac4e60)

app: &{{/invitations 127.0.0.1:3000 http://127.0.0.1:3000 development debug {%!s(*logrus.Logger=&{0xc0000ce008 map[] 0xc0000aac60 false 5 {{0 0} false} {{} 0xc000208400 8 <nil> 0 <nil>} 0x4e93a0})} %!s(http.HandlerFunc=0xa92460) %!s(*sessions.CookieStore=&{[0xc0004c35f0] 0xc0004b2700}) _catalyst_interview_session %!s(int=60) %!s(*worker.Simple=&{{0xc0003d0e00} 0xc00004ab40 0x4fd2a0 map[] 0xc0000aab68 {{} 0 0} true}) %!s(bool=false) [] [] %!s(bool=false) /invitations/{invitation_id} context.Background.WithCancel.WithCancel %!s(context.CancelFunc=0x4fd2a0)} {%!s(*buffalo.App=&{{/ 127.0.0.1:3000 http://127.0.0.1:3000 development 5 {0xc0003d0e00} 0xa92460 0xc0004b54c0 _catalyst_interview_session 60 0xc000100320 false [] [] false 0xc0004b26c0 0x4fd2a0} {0xc000200000 0xc000200000 / http://127.0.0.1:3000 0xc0004b54e0 map[404:0xa90500 500:0xa90500] 0xc0006a2240 [/]} 0xc0006c27c8 [0xc000198980 0xc000198b80 0xc000198c00 0xc000198c80 0xc000198d00 0xc000198d80 0xc000198e00 0xc000198e80] <nil> [0xc0002001c0] {}}) %!s(*buffalo.App=&{{/invitations 127.0.0.1:3000 http://127.0.0.1:3000 development 5 {0xc0003d0e00} 0xa92460 0xc0004b54c0 _catalyst_interview_session 60 0xc000100320 false [] [] false /invitations/{invitation_id} 0xc0004b2840 0x4fd2a0} {0xc000200000 0xc0002001c0 /invitations http://127.0.0.1:3000 /invitations/{invitation_id} 0xc000278640 map[404:0xa90500 500:0xa90500] 0xc0006a2240 []} 0xc0006c2f48 [] 0xc000200000 [] {}}) /invitations http://127.0.0.1:3000 /invitations/{invitation_id} github.com/gobuffalo/buffalo.*App.defaultErrorMiddleware
github.com/gobuffalo/buffalo.*App.PanicHandler
github.com/gobuffalo/buffalo.RequestLoggerFunc
github.com/gobuffalo/mw-forcessl.Middleware.func1
github.com/gobuffalo/mw-paramlogger.ParameterLogger
github.com/gobuffalo/mw-csrf.glob..func1
github.com/gobuffalo/buffalo-pop/v3/pop/popmw.Transaction.func2
github.com/gobuffalo/mw-i18n/v2.*Translator.Middleware.func1 map[%!s(int=404):%!s(buffalo.ErrorHandler=0xa90500) %!s(int=500):%!s(buffalo.ErrorHandler=0xa90500)] %!s(*mux.Router=&{0xa8cb40 0xa8cb40 [0xc0000a3360 0xc0000a3f40 0xc0003906e0 0xc000390b40 0xc000390f00 0xc000391540 0xc000391b80 0xc0003f01e0 0xc0003f0820] map[] false [] {false false false {<nil> <nil> []} [] <nil>}}) []} %!s(*sync.RWMutex=&{{0 0} 0 0 0 0}) [] %!s(*buffalo.App=&{{/ 127.0.0.1:3000 http://127.0.0.1:3000 development 5 {0xc0003d0e00} 0xa92460 0xc0004b54c0 _catalyst_interview_session 60 0xc000100320 false [] [] false 0xc0004b26c0 0x4fd2a0} {0xc000200000 0xc000200000 / http://127.0.0.1:3000 0xc0004b54e0 map[404:0xa90500 500:0xa90500] 0xc0006a2240 [/]} 0xc0006c27c8 [0xc000198980 0xc000198b80 0xc000198c00 0xc000198c80 0xc000198d00 0xc000198d80 0xc000198e00 0xc000198e80] <nil> [0xc0002001c0] {}}) [] {}}

authenticity_token: /Iu6PFXMRQ8lCei3+FNmBIF7N+lghluvJVACA69t+/xV8id0l/OO9DBkwqBjZ/sf+9v5cPStktBpTvOZfhoffQ==

contentType: text/html

current_path: /invitations/new/

current_route: {
"method": "GET",
"path": "/invitations/new/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.New",
"resourceName": "InvitationsResource",
"pathName": "newInvitationsPath",
"aliases": []
}

env: development

invitation: {"id":"00000000-0000-0000-0000-000000000000","token":"","expired_at":"0001-01-01T00:00:00Z","recalled":false,"total_login":0,"created_at":"0001-01-01T00:00:00Z","updated_at":"0001-01-01T00:00:00Z"}

languages: [en-US en zh-CN zh-TW zh ms en-US]

method: GET

request_id: 0d6cecff581e977fc542-5bbcb0759286b00b499a

routes: [{
"method": "GET",
"path": "/",
"handler": "adamtang79/catalyst_interview/actions.HomeHandler",
"pathName": "rootPath",
"aliases": []
} {
"method": "GET",
"path": "/invitations/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.List",
"resourceName": "InvitationsResource",
"pathName": "invitationsPath",
"aliases": []
} {
"method": "POST",
"path": "/invitations/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.Create",
"resourceName": "InvitationsResource",
"pathName": "invitationsPath",
"aliases": []
} {
"method": "GET",
"path": "/invitations/new/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.New",
"resourceName": "InvitationsResource",
"pathName": "newInvitationsPath",
"aliases": []
} {
"method": "GET",
"path": "/invitations/{invitation_id}/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.Show",
"resourceName": "InvitationsResource",
"pathName": "invitationPath",
"aliases": []
} {
"method": "PUT",
"path": "/invitations/{invitation_id}/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.Update",
"resourceName": "InvitationsResource",
"pathName": "invitationPath",
"aliases": []
} {
"method": "DELETE",
"path": "/invitations/{invitation_id}/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.Destroy",
"resourceName": "InvitationsResource",
"pathName": "invitationPath",
"aliases": []
} {
"method": "GET",
"path": "/invitations/{invitation_id}/edit/",
"handler": "adamtang79/catalyst_interview/actions.InvitationsResource.Edit",
"resourceName": "InvitationsResource",
"pathName": "editInvitationPath",
"aliases": []
}]

t: %!s(func(string, ...interface {}) string=0xac6860)

tx: catalyst_interview_development:DonAsk123@Me@(localhost:3306)/catalyst_interview_development?readTimeout=3s&collation=utf8mb4_general_ci&parseTime=true&multiStatements=true"

Parameters: "map[]"

Headers: "Accept-Encoding: [gzip, deflate, br]

Accept-Language: [en-US,en;q=0.9,zh-CN;q=0.8,zh-TW;q=0.7,zh;q=0.6,ms;q=0.5]

Accept: [text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9]

Cache-Control: [max-age=0]

Connection: [keep-alive]

Cookie: [fbm_2872250886408569=base_domain=; _catalystinvite_session=MTY1OTY1MDEzM3xEdi1CQkFFQ180SUFBUkFCRUFBQV82UF9nZ0FEQm5OMGNtbHVad3dVQUJKaGRYUm9aVzUwYVdOcGRIbGZkRzlyWlc0SFcxMTFhVzUwT0FvaUFDQUtkekhScFNkem9oc2RXSkxMV3RGQkIwMllqUmwweGpCM3Z2ZTlIYWRlYlFaemRISnBibWNNQ1FBSFgyWnNZWE5vWHdkYlhYVnBiblE0Q2dRQUFudDlCbk4wY21sdVp3d09BQXh5WlhGMVpYTjBiM0pmYVdRR2MzUnlhVzVuREJZQUZESmpZemd4WTJZNU5XSXlObVF6TmpjeVlUWm18djmq-1mT5_45loEQnjkSisUIp8q6UXzpo85o0VjFRhc=; _bffalo_session=MTY1OTY1ODc4MHxEdi1CQkFFQ180SUFBUkFCRUFBQV82UF9nZ0FEQm5OMGNtbHVad3dVQUJKaGRYUm9aVzUwYVdOcGRIbGZkRzlyWlc0SFcxMTFhVzUwT0FvaUFDQ09wczZmREZyTkJYMXZTcDN3ck1IOWhIVVI5c1BFdV9iZFBMZHhUdGpWZHdaemRISnBibWNNQ1FBSFgyWnNZWE5vWHdkYlhYVnBiblE0Q2dRQUFudDlCbk4wY21sdVp3d09BQXh5WlhGMVpYTjBiM0pmYVdRR2MzUnlhVzVuREJZQUZEaG1NbVV5TldWak5EQXhOakEzWXpNME56bGh88w1NvrrgI5yTC8UN6Oa8Xe2mdIiga8k9niDKvbqcBPs=; _catalyst_invite_session=MTY1OTY2NzgzOHxEdi1CQkFFQ180SUFBUkFCRUFBQV82UF9nZ0FEQm5OMGNtbHVad3dKQUFkZlpteGhjMmhmQjF0ZGRXbHVkRGdLQkFBQ2UzMEdjM1J5YVc1bkRBNEFESEpsY1hWbGMzUnZjbDlwWkFaemRISnBibWNNRmdBVVlXTTBZamd6WlRKbFpERXdabVV6TmpBMllUZ0djM1J5YVc1bkRCUUFFbUYxZEdobGJuUnBZMmwwZVY5MGIydGxiZ2RiWFhWcGJuUTRDaUlBSUg3OW44UldOeE11N2gya3NrMVVWUmx4NW94MjFaRWwzaUFqV2dUVUI1OWt86DmvLGDHOETeJ4Nzju0iJnYYqZ9gcNlB1Z0TPRnIvz4=; _catalyst_interview_session=MTY1OTczOTgxMXxEdi1CQkFFQ180SUFBUkFCRUFBQV82UF9nZ0FEQm5OMGNtbHVad3dKQUFkZlpteGhjMmhmQjF0ZGRXbHVkRGdLQkFBQ2UzMEdjM1J5YVc1bkRBNEFESEpsY1hWbGMzUnZjbDlwWkFaemRISnBibWNNRmdBVU1HUTJZMlZqWm1ZMU9ERmxPVGMzWm1NMU5ESUdjM1J5YVc1bkRCUUFFbUYxZEdobGJuUnBZMmwwZVY5MGIydGxiZ2RiWFhWcGJuUTRDaUlBSUtsNW5VakNQOHY3RlcwcUY1czBuUnQ2b002WmxDdkpmMHdlOFpyUmQtU0J8ihM4Rh5id-lofkUkb-FWFcb1bnb6YJ4NQRhAXWLfcI8=]

Referer: [http://localhost:3000/invitations/]

Sec-Ch-Ua-Mobile: [?0]

Sec-Ch-Ua-Platform: ["Windows"]

Sec-Ch-Ua: ["Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"]

Sec-Fetch-Dest: [document]

Sec-Fetch-Mode: [navigate]

Sec-Fetch-Site: [same-origin]

Sec-Fetch-User: [?1]

Upgrade-Insecure-Requests: [1]

User-Agent: [Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36]"

### Info

Please run `buffalo info` and paste the information below where it says "PASTE_HERE".

<details>

```
-> Go: Checking installation
←[32m✓ The `go` executable was found on your system at: C:\Program Files\Go\bin\go.exe←[0m

-> Go: Checking minimum version requirements
←[32m✓ Your version of Go, 1.18.4, meets the minimum requirements.←[0m

-> Go: Checking Package Management
←[32m✓ You are using Go Modules (`go`) for package management.←[0m

-> Go: Checking PATH
←[32m✓ Your PATH contains C:\Users\adamtang\go/bin.←[0m

-> Node: Checking installation
←[32m✓ The `node` executable was found on your system at: C:\Program Files\nodejs\node.exe←[0m

-> Node: Checking minimum version requirements
←[32m✓ Your version of Node, v16.16.0, meets the minimum requirements.←[0m

-> NPM: Checking installation
←[32m✓ The `npm` executable was found on your system at: C:\Program Files\nodejs\npm.cmd←[0m

-> NPM: Checking minimum version requirements
←[31m✘ Invalid Semantic Version←[0m

-> Yarn: Checking installation
←[32m✓ The `yarnpkg` executable was found on your system at: C:\Program Files\nodejs\yarnpkg.cmd←[0m

-> Yarn: Checking minimum version requirements
←[32m✓ Your version of Yarn, 1.22.15, meets the minimum requirements.←[0m

-> PostgreSQL: Checking installation
←[31m✘ The `postgres` executable could not be found on your system.←[0m
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
←[31m✘ The `mysql` executable could not be found on your system.←[0m
For help setting up your MySQL environment please follow the instructions for you platform
at:

https://www.mysql.com/downloads/

-> SQLite3: Checking installation
←[31m✘ The `sqlite3` executable could not be found on your system.←[0m
For help setting up your SQLite3 environment please follow the instructions for you platform at:

https://www.sqlite.org/download.html

-> Cockroach: Checking installation
←[31m✘ The `cockroach` executable could not be found on your system.←[0m
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
←[32m✓ The `buffalo` executable was found on your system at: C:\Users\adamtang\go\bin\buffalo.exe←[0m

-> Buffalo (CLI): Checking minimum version requirements
←[32m✓ Your version of Buffalo (CLI), v0.18.8, meets the minimum requirements.←[0m

-> Buffalo: Application Details
Pwd         D:\adt_prj\adt_79\ctlitv\github\vscode\branch\poc_draft
Root        D:\adt_prj\adt_79\ctlitv\github\vscode\branch\poc_draft
GoPath      C:\Users\adamtang\go
PackagePkg  adamtang79/catalyst_interview
ActionsPkg  adamtang79/catalyst_interview/actions
ModelsPkg   adamtang79/catalyst_interview/models
GriftsPkg   adamtang79/catalyst_interview/grifts
WithModules true
Name        catalyst_interview
Bin         bin\catalyst_interview
VCS         git
WithPop     true
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    false
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack --mode production --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "catalyst_interview"
bin = "bin\\catalyst_interview"
vcs = "git"
with_pop = true
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = false
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop/v3@latest"

-> Buffalo: go.mod
module adamtang79/catalyst_interview

go 1.18

require (
        github.com/gobuffalo/buffalo v0.18.9
        github.com/gobuffalo/buffalo-pop/v3 v3.0.6
        github.com/gobuffalo/envy v1.10.1
        github.com/gobuffalo/grift v1.5.1
        github.com/gobuffalo/mw-csrf v1.0.1
        github.com/gobuffalo/mw-forcessl v1.0.1
        github.com/gobuffalo/mw-i18n/v2 v2.0.2
        github.com/gobuffalo/mw-paramlogger v1.0.1
        github.com/gobuffalo/pop/v6 v6.0.6
        github.com/gobuffalo/suite/v4 v4.0.3
        github.com/gobuffalo/validate/v3 v3.3.2
        github.com/gobuffalo/x v0.1.0
        github.com/gofrs/uuid v4.2.0+incompatible
        github.com/unrolled/secure v1.12.0
)

require (
        github.com/BurntSushi/toml v1.1.0 // indirect
        github.com/Masterminds/semver/v3 v3.1.1 // indirect
        github.com/aymerick/douceur v0.2.0 // indirect
        github.com/davecgh/go-spew v1.1.1 // indirect
        github.com/dustin/go-humanize v1.0.0 // indirect
        github.com/fatih/color v1.13.0 // indirect
        github.com/fatih/structs v1.1.0 // indirect
        github.com/felixge/httpsnoop v1.0.1 // indirect
        github.com/fsnotify/fsnotify v1.5.4 // indirect
        github.com/go-sql-driver/mysql v1.6.0 // indirect
        github.com/gobuffalo/events v1.4.2 // indirect
        github.com/gobuffalo/fizz v1.14.2 // indirect
        github.com/gobuffalo/flect v0.2.5 // indirect
        github.com/gobuffalo/github_flavored_markdown v1.1.1 // indirect
        github.com/gobuffalo/helpers v0.6.5 // indirect
        github.com/gobuffalo/httptest v1.5.1 // indirect
        github.com/gobuffalo/logger v1.0.6 // indirect
        github.com/gobuffalo/meta v0.3.2 // indirect
        github.com/gobuffalo/nulls v0.4.1 // indirect
        github.com/gobuffalo/plush/v4 v4.1.13 // indirect
        github.com/gobuffalo/refresh v1.13.1 // indirect
        github.com/gobuffalo/tags/v3 v3.1.3 // indirect
        github.com/gorilla/css v1.0.0 // indirect
        github.com/gorilla/handlers v1.5.1 // indirect
        github.com/gorilla/mux v1.8.0 // indirect
        github.com/gorilla/securecookie v1.1.1 // indirect
        github.com/gorilla/sessions v1.2.1 // indirect
        github.com/inconshreveable/mousetrap v1.0.0 // indirect
        github.com/jackc/chunkreader/v2 v2.0.1 // indirect
        github.com/jackc/pgconn v1.12.1 // indirect
        github.com/jackc/pgio v1.0.0 // indirect
        github.com/jackc/pgpassfile v1.0.0 // indirect
        github.com/jackc/pgproto3/v2 v2.3.0 // indirect
        github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b // indirect
        github.com/jackc/pgtype v1.11.0 // indirect
        github.com/jackc/pgx/v4 v4.16.1 // indirect
        github.com/jmoiron/sqlx v1.3.5 // indirect
        github.com/joho/godotenv v1.4.0 // indirect
        github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51 // indirect
        github.com/luna-duclos/instrumentedsql v1.1.3 // indirect
        github.com/mattn/go-colorable v0.1.9 // indirect
        github.com/mattn/go-isatty v0.0.14 // indirect
        github.com/mattn/go-sqlite3 v1.14.14 // indirect
        github.com/microcosm-cc/bluemonday v1.0.16 // indirect
        github.com/mitchellh/go-homedir v1.1.0 // indirect
        github.com/monoculum/formam v3.5.5+incompatible // indirect
        github.com/nicksnyder/go-i18n v1.10.1 // indirect
        github.com/pelletier/go-toml v1.2.0 // indirect
        github.com/pkg/errors v0.9.1 // indirect
        github.com/pmezard/go-difflib v1.0.0 // indirect
        github.com/rogpeppe/go-internal v1.8.1 // indirect
        github.com/sergi/go-diff v1.2.0 // indirect
        github.com/sirupsen/logrus v1.8.1 // indirect
        github.com/sourcegraph/annotate v0.0.0-20160123013949-f4cad6c6324d // indirect
        github.com/sourcegraph/syntaxhighlight v0.0.0-20170531221838-bd320f5d308e // indirect
        github.com/spf13/cobra v1.5.0 // indirect
        github.com/spf13/pflag v1.0.5 // indirect
        github.com/stretchr/testify v1.8.0 // indirect
        golang.org/x/crypto v0.0.0-20220622213112-05595931fe9d // indirect
        golang.org/x/net v0.0.0-20211112202133-69e39bad7dc2 // indirect
        golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f // indirect
        golang.org/x/sys v0.0.0-20220412211240-33da011f77ad // indirect
        golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 // indirect
        golang.org/x/text v0.3.7 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
        gopkg.in/yaml.v3 v3.0.1 // indirect
)
```

</details>

**Comment by sio4** [comment]
Could you provide the result of the following two commands? (It seems like your development environment is Windows. Please post the output of equivalent commands)

- `ls -Rl your_app/templates`
- `cat your_app/templates/invitations/new.plush.html`

The template included for the `new` page should be `invitations/form.html` but the error message indicated it could not find `invitations_form.html` so I wonder why the path of partial is different.

> Error Trace: "invitations/new.plush.html: line 6: could not call formFor function: could not call partial function: could not find template invitations_form.html"

Also, the current version of CLI is v0.18.8 but the version string is not correctly updated, so the version should be printed as v0.18.7. Could you please also post the output of `buffalo version` command and also what was your installation method of the tool?

>←[32m✓ Your version of Buffalo (CLI), v0.18.8, meets the minimum requirements.←[0m

**Comment by sio4** [comment]
> Also, the current version of CLI is v0.18.8 but the version string is not correctly updated, so the version should be printed as v0.18.7. Could you please also post the output of `buffalo version` command and also what was your installation method of the tool?

Please ignore this but just confirm if you installed the CLI with the official binary distritution.
