### ISSUE TITLE
add a example of this usage in the scaffolded app

### ISSUE THREAD

**Issue by sio4** [gobuffalo/cli#238]
Having an example on the scaffolded app could be nice. At least we need a document section for this.

```go
		paramlogger.ParameterExclusionList = append(paramlogger.ParameterExclusionList, "passwd", "pass")
		// or paramlogger.ParameterExclusionList = []string{"passwd", "pass"}
```

_Originally posted by @sio4 in https://github.com/gobuffalo/mw-paramlogger/pull/7#pullrequestreview-1136085632_

**Comment by paganotoni** [comment]
Added https://github.com/gobuffalo/mw-paramlogger/pull/11

**Comment by sio4** [comment]
Having examples on the scaffolded app could be nice but we cannot add all examples. Now I think gobuffalo/mw-paramlogger#11 could be fine for now. We can strengthen the official document someday.
