### ISSUE TITLE
bug: docker image is broken

### ISSUE THREAD

**Issue by vitr** [gobuffalo/cli#249]
### Description

I wasn't following the project for a while, but it looks like the new maintainers have managed to break very basic things. Like this one docker image used to work perfectly https://blog.gobuffalo.io/buffalo-docker-images-ff3938dcaa53
Now it has this error when you try to run buffalo inside the container:
```
bash: /go/bin/buffalo: cannot execute binary file: Exec format error
```
I understand the challenges of open-source, and ready to help with fixing the image if the project is still alive and somebody cares about it.

### To Reproduce

```
docker run -it -p "3000:3000" gobuffalo/buffalo:latest "/bin/bash"
buffalo new --db-type=sqlite3 coke
```

**Comment by paganotoni** [comment]
This is solved in v0.18.11
