### ISSUE TITLE
bug: Dependency upgrade and Version fix?

### ISSUE THREAD

**Issue by saurori** [gobuffalo/cli#251]
### Description

Would it be possible to upgrade go modules and do a version release? A number of libraries are out of date. I am specifically interested in https://github.com/gobuffalo/refresh for [v1.13.3](https://github.com/gobuffalo/refresh/releases/tag/v1.13.3) that fixes [#6](https://github.com/gobuffalo/refresh/issues/6).

Also, the Version reported by `buffalo version` is incorrect. Current is `v0.18.12` but [version.go](https://github.com/gobuffalo/cli/blob/fb755f43a9f07496758ab87fee776ad9e63cfca4/internal/runtime/version.go#L4) is reporting `v0.18.9`.

**Comment by sio4** [comment]
Sorry for the long waiting. Will work on it with higher priority!

**Comment by sio4** [comment]
Hi @saurori long wating!
I just merged the fix and will release v0.18.13. Please take a test and let me know if the issue still exists!

**Comment by saurori** [comment]
@sio4 Thank you! Everything is working now and my issue with `buffalo dev` not reloading is fixed. Also the version number is now correct.
