### ISSUE TITLE
cli generates `Dockerfile` contains a wrong buffalo version

### ISSUE THREAD

**Issue by sio4** [gobuffalo/cli#37]
### Description

What is the policy of versioning? Do we keep the versions of "buffalo" and "cli" match with each other? I think that could be good to prevent confusion on the user side but it could be hard to keep them as the same especially when one of them has a relatively higher development speed.

As of today, the version of buffalo is 0.17.3 and the version of cli is 0.17.5. The cli generates `Dockerfile` as if we have buffalo v0.17.5, also `buffalo version` only prints cli version.

```Dockerfile
FROM gobuffalo/buffalo:v0.17.5 as builder
<...>
```

Maybe we need to add something like `BuffaloVersion` or `CLIVersion`. What do you think?

```go
// Version is the current version of the buffalo binary
var Version = "v0.17.5"
var BuffaloVersion = "v0.17.3"
```

### Steps to Reproduce the Problem

  1. install newest version of buffalo cli which is 0.17.5
  2. run `buffalo new app`
  3. check `Dockerfile`

### Expected Behavior

Generated usable `Dockerfile`.

### Actual Behavior

Generated `Dockerfile` with wrong version (since buffalo version is still 0.17.3)

### Info

<details>

```
-> Go: Checking installation
✓ The `go` executable was found on your system at: /opt/google/go/bin/go

-> Go: Checking minimum version requirements
✓ Your version of Go, 1.16.7, meets the minimum requirements.

-> Go: Checking Package Management
✓ You are using Go Modules (`go`) for package management.

-> Go: Checking PATH
✓ Your PATH contains /home/sio4/go/bin.

-> Node: Checking installation
✓ The `node` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/node

-> Node: Checking minimum version requirements
✓ Your version of Node, v14.17.6, meets the minimum requirements.

-> NPM: Checking installation
✓ The `npm` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/npm

-> NPM: Checking minimum version requirements
✓ Your version of NPM, 6.14.15, meets the minimum requirements.

-> Yarn: Checking installation
✓ The `yarnpkg` executable was found on your system at: /home/sio4/.nvm/versions/node/v14.17.6/bin/yarnpkg

-> Yarn: Checking minimum version requirements
✓ Your version of Yarn, 1.22.11, meets the minimum requirements.

-> PostgreSQL: Checking installation
✘ The `postgres` executable could not be found on your system.
For help setting up your Postgres environment please follow the instructions for you platform at:

https://www.postgresql.org/download/

-> MySQL: Checking installation
✓ The `mysql` executable was found on your system at: /usr/bin/mysql

-> MySQL: Checking minimum version requirements
✓ Your version of MySQL, 8.0.26, meets the minimum requirements.

-> SQLite3: Checking installation
✓ The `sqlite3` executable was found on your system at: /usr/bin/sqlite3

-> SQLite3: Checking minimum version requirements
✓ Your version of SQLite3, 3.31.1, meets the minimum requirements.

-> Cockroach: Checking installation
✘ The `cockroach` executable could not be found on your system.
For help setting up your Cockroach environment please follow the instructions for you platform at:

https://www.cockroachlabs.com/docs/stable/

-> Buffalo (CLI): Checking installation
✓ The `buffalo` executable was found on your system at: /home/sio4/go/bin/buffalo

-> Buffalo (CLI): Checking minimum version requirements
✓ Your version of Buffalo (CLI), v0.17.5, meets the minimum requirements.

-> Buffalo: Application Details
Pwd         /home/sio4/git/hyeoncheon/coke
Root        /home/sio4/git/hyeoncheon/coke
GoPath      /home/sio4/go
PackagePkg  coke
ActionsPkg  coke/actions
ModelsPkg   coke/models
GriftsPkg   coke/grifts
WithModules true
Name        coke
Bin         bin/coke
VCS         git
WithPop     false
WithSQLite  false
WithDep     false
WithWebpack true
WithNodeJs  true
WithYarn    true
WithDocker  true
WithGrifts  true
AsWeb       true
AsAPI       false
InApp       true
PackageJSON {map[build:webpack --mode production --progress dev:webpack --watch]}

-> Buffalo: config/buffalo-app.toml
name = "coke"
bin = "bin/coke"
vcs = "git"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false

-> Buffalo: config/buffalo-plugins.toml

-> Buffalo: go.mod
module coke

go 1.16

require (
	github.com/gobuffalo/buffalo v0.17.3
	github.com/gobuffalo/envy v1.9.0
	github.com/gobuffalo/mw-csrf v1.0.0
	github.com/gobuffalo/mw-forcessl v0.0.0-20200131175327-94b2bd771862
	github.com/gobuffalo/mw-i18n v1.1.0
	github.com/gobuffalo/mw-paramlogger v1.0.0
	github.com/gobuffalo/packr/v2 v2.8.1
	github.com/gobuffalo/suite v2.8.2+incompatible
	github.com/unrolled/secure v1.0.9
)
```

</details>

**Comment by sio4** [comment]
Keep this issue open please :-)

**Comment by sio4** [comment]
One idea is updating the version with the version of buffalo after generating the Dockerfile, run `go mod tidy`, and get the version from module dependency information. I thought `here` can help us, but it seems like `here` only gives the name of modules but not the version of them. :-(

For now, hardcoded coupling (as suggested above) + document (and short help message) could be a solution for now.

**Comment by paganotoni** [comment]
Solved in v0.17.6, from now on the Docker images will be generated from the CLI project instead of the Buffalo one.

**Comment by sio4** [comment]
Hi @paganotoni, I think the version mismatch happens because the cli uses its own version when parsing the Dockerfile template it has. I believe the file below is the file,

https://github.com/gobuffalo/cli/blob/3198ed2dbc08e5d972950104269d1447192d2be6/internal/genny/docker/templates/multi/Dockerfile.tmpl#L3

and the value of `opts.Version` came from `runtime.Version` which is the version of buffalo cli, but buffalo core.
With these findings, I suggested if we can have something like `opts.core.Version` even though hardcoded coupling is not a great idea.

https://github.com/gobuffalo/cli/blob/3198ed2dbc08e5d972950104269d1447192d2be6/internal/runtime/version.go#L4

Or, I think that just simply using the latest version of Docker image could be a quick and dirty solution. :-)

What do you think?

**Comment by sio4** [comment]
The following could be a quick fix for this issue:

```diff
--- a/internal/genny/docker/options.go
+++ b/internal/genny/docker/options.go
@@ -19,7 +19,7 @@ func (opts *Options) Validate() error {
                opts.App = meta.New(".")
        }
        if len(opts.Version) == 0 {
-               opts.Version = runtime.Version
+               opts.Version = runtime.BuffaloVersion
        }
        if len(opts.Style) == 0 {
                opts.Style = "multi"
--- a/internal/runtime/version.go
+++ b/internal/runtime/version.go
@@ -2,3 +2,4 @@ package runtime
 
 // Version is the current version of the buffalo binary
 var Version = "v0.17.6"
+var BuffaloVersion = "v0.17.4"
```

By the way, I feel like it could be better if `meta` (or `here`) provides buffalo version information for the current application but according to what I found about the direction of `meta/v2` (gobuffalo/meta#11), buffalo version could not be included in `meta` since it is not a buffalo specific but a universal meta.

On the other hand, the docker image is for building not for runtime/compilation dependency so version mismatch could not be a huge issue if the image exists (by hardcoded coupling).

What do you think? If maintainers agree on my quick fix, I will include this patch into my future PR (which will follow gobuffalo/buffalo#2152)

**Comment by paganotoni** [comment]
Given we've separated the CLI from the Go library we might have 2 versions, one for the CLI and one for the tool. One thing to note here is that when the CLI is being asked `version`, I would say the version we're hoping to see is the CLI version. The `gobuffalo/buffalo` version is defined by the go.mod in the package and you could get it from there.

**Comment by fasmat** [comment]
@paganotoni I think this is resolved with 0.18.0?

**Comment by sio4** [comment]
No, this is still an existing issue if you did not fix it. My current plan (idea) is that meta or Clara or some extended thing can automatically catch the current `buffalo` version from `go.mod` and use it when the user runs `buffalo new` or equivalant.

**Comment by sio4** [comment]
Anyway, since the CLI version and buffalo core version is the same today, the user will not affect this issue for now.

**Comment by fasmat** [comment]
afaik @paganotoni changed the versioning of the Docker images to match the version of the `gobuffalo/cli` binary and not the `gobuffalo/buffalo` library with 0.17.5 and new versions of docker images are now released with new versions of the CLI not the library.

That would also solve the issue, or would you prefer the solution you suggested?

**Comment by paganotoni** [comment]
I think that solves the issue, lets close this one.

**Comment by sio4** [comment]
Ah! I misunderstood the comment https://github.com/gobuffalo/cli/issues/37#issuecomment-965931303 before.

That makes sense since the Docker image is a part of the build tool so following the CLI version could be a good thing. (Also, when the user installs buffalo, it is actually installing the CLI, buffalo core is just automatically downloaded for the user's app, and the user actually doesn't care about the version of core...)

By this, I just realized which version mostly represents the version of the whole gobuffalo project when we talk about `v1` things. It should be the CLI version and the buffalo core library version could be treated as the same as other modules versions. e.g. pop/v6 or genny/v2.
