### ISSUE TITLE
"unable to find pop config file" error only appears in pre-built binaries of gobuffalo cli

### ISSUE THREAD

**Issue by fasmat** [gobuffalo/cli#38]
### Description

I ran into an issue that has been reported before but apparently was never fixed. Whenever I build my application with `buffalo build` and try to execute the binary it exits with the error message "unable to find pop config file" unless there is a `database.yml` in the same folder as the binary. Here are links to other issues reporting this problem:

https://github.com/gobuffalo/buffalo/issues/1682
https://github.com/gobuffalo/cli/issues/19

Interestingly I never ran into the issue when I used the provided multi-stage Dockerfile to build my project, although the generated image does not contain a `database.yml` file.

The issue seems to be the pre-built binaries released on github. When I install the buffalo cli from source the problem does not happen. This also explains why it works with the multi-stage Dockerfile; the buffalo cli there is installed using `go install` instead of downloading it from the github releases.

### Steps to Reproduce the Problem

  1. Install buffalo cli from the github releases: https://github.com/gobuffalo/cli/releases/tag/v0.17.5 (I've been testing with the linux x86_64 build)
  2. Generate a new project with `buffalo new coke`
  3. Build the project with `buffalo build -o bin/app`
  4. If you now move the generated binary from `bin` to any folder outside the working space and start it it will exit with the error `unable to find pop config file`
  5. Install the gobuffalo cli with `go install github.com/gobuffalo/cli/cmd/buffalo@v0.17.5`
  6. Build the project with `buffalo build -o bin/app`
  7. This binary will work in any folder you place it and will not produce the `unable to find pop config file` error that the other binary has.

### Expected Behavior

Both the pre-built binary on github as well as the local binary generated with `go install` should behave the same.

### Actual Behavior

The pre-built binary seems to have an issue with how it packs files in the binary using `packr`.

### Info

I tested the pre-built binary with version v0.17.5 (form https://github.com/gobuffalo/cli/releases/tag/v0.17.5) and the gobuffalo cli installed with `go install github.com/gobuffalo/cli/cmd/buffalo@v0.17.5`.

**Comment by fasmat** [comment]
Bump for visibility

**Comment by fasmat** [comment]
This issue is resolved in 0.18.0

**Comment by paxer** [comment]
I see this issue happening when compiling for Linux with buffalo CLI installed via homebrew on macOS

```
❯ buffalo version
INFO[0000] Buffalo version is: v0.18.14
```
The compiled binary on Linux when executed, shows `unable to find pop config file`

P.S. We're deploying a single binary (not Docker) to AWS Beanstalk, and we had to add `database.yml` to the package to avoid this error...
