### ISSUE TITLE
stabilizing the new release 

### ISSUE THREAD

**Issue by sio4** [gobuffalo/cli#63]
Known issue and stabilizing the new release

- [x] (hot) leading slash for `r.HTML()` - released as buffalo v0.18.1
    - gobuffalo/buffalo#2178
- [X] (hot) `_partial` templates missing
    - gobuffalo/cli#57
- [x] (hot) for the very first `buffalo dev`, asset loadding fails
- [x] (hot) live file loading/updating for dev
- [x] (warm) http://127.0.0.1:3000/embed.go
    - gobuffalo/buffalo#2180
    - gobuffalo/cli#60 
- [x] #65
    - https://github.com/gobuffalo/pop/pull/677
    - https://github.com/gobuffalo/buffalo-pop/pull/33
- [x] (cold) running `buffalo info` in a non-buffalo app directoy creates empty `config` dir.
    - #68
- [x] (warm) pop version string is not match with the actual version
    - https://github.com/gobuffalo/pop/pull/675
- [x] (cold) b.g.resource generated actions and models has spaces instead of tabs
    - [x] for actions
    - [x] for models
        - https://github.com/gobuffalo/pop/pull/677
- [x] (hot) `buffalo build` failed when a go-built binary is within the source tree.
    - [x] also `buffalo build` scans everything in the source tree for "template validation"
    - #62
    - #64
- [x] (hot) #56 for pop disabled app
    - #67

**Comment by sio4** [comment]
- gobuffalo/buffalo#2180 and gobuffalo/cli#60 for things related to `embed.FS`. Now `buffalo.FS`!
- gobuffalo/buffalo#2178 for `r.HTML()` issue
- gobuffalo/cli#57 for a partial missing issue

**Comment by fasmat** [comment]
The current ``//go:embed */*`` causes issues and doesn't include all files that should be included:

https://github.com/gobuffalo/cli/pull/57#issuecomment-981251949

The only way around this I see is to add multiple embed directives when generating a new model and ensure that empty folders contain a `keep` file so embed doesn't complain that they contain no files.

**Comment by sio4** [comment]
Yeah, the current approach cannot handle all cases but your approach may not easily help that situation. For the situation of the comment, one additional subdirectory such as `templates/content/shared/_partial`, we could add an empty folder with a placeholder for all generated models even though they will not be used for most of the users but how about more depth?

I think the only effective way to help users for this situation is just to document it both in gobuffalo.io and the `embed.go` file.

templates/embed.go 
```go
package templates

import (
	"embed"
	"io/fs"

	"github.com/gobuffalo/buffalo"
)

// if you have non-standard subdirectories, you need to add another go:embed directive for them.
//go:embed * */*
var files embed.FS

func FS() fs.FS {
	return buffalo.NewFS(files, "templates")
}
```
locales/embed.go 
```go
package locales

import (
	"embed"
	"io/fs"

	"github.com/gobuffalo/buffalo"
)

// locale files should have extension `yaml` and be placed in this directory
//go:embed *.yaml
var files embed.FS

func FS() fs.FS {
	return buffalo.NewFS(files, "locales")
}
```
public/embed.go 
```go
package public

import (
	"embed"
	"io/fs"

	"github.com/gobuffalo/buffalo"
)

// currently files started with `.` and `_` will not be automatically included.
// if you need them to be included, add go:embed directive for them here.
//go:embed *
var files embed.FS

func FS() fs.FS {
	return buffalo.NewFS(files, "public")
}
```

**Comment by paganotoni** [comment]
@sio4 is there anything you guys need from me on this one?

**Comment by sio4** [comment]
> @sio4 is there anything you guys need from me on this one?

Yes, there are some pending PRs to be merged and released. Once PRs for pop merged and released as 6.0.1, will PR for buffalo-pop.

**Comment by paganotoni** [comment]
@sio4 https://github.com/gobuffalo/pop/releases/tag/v6.0.1 released.

**Comment by sio4** [comment]
Thanks @paganotoni!
Just requested a PR for buffalo-pop gobuffalo/buffalo-pop#33
Then all listed issues are covered!

**Comment by paganotoni** [comment]
I just merged it. Thanks @sio4 Looking forward for our next steps :).

**Comment by sio4** [comment]
Wow! thanks for the lightning-fast merging and releasing!
