### ISSUE TITLE
Upgrading buffalo app (0.18.1) fails with template error

### ISSUE THREAD

**Issue by skoslitz** [gobuffalo/cli#80]
```
~~~ Rewriting Imports ~~~
~~~ Checking webpack.config.js ~~~
Usage:
  buffalo fix [flags]

Aliases:
  fix, update

Flags:
  -h, --help   help for fix
  -y, --y      update all without asking for confirmation

ERRO[0007] Error: template: "webpack" is an incomplete or empty template
```

Previous buffalo version is v0.15.5, actual go version 1.17.3
`Buffalo info` gives no errors.

**Comment by Rohrschacht** [comment]
It seems I have identified the issue to be that the name given to template.New() has to be the same name of the file in the embedded FS, although that is also given to ParseFS. It seems I have solved it in 35bf6e7, it does not give me the "incomplete or empty template" error anymore when I try to `fix`. Shall I open a PR?
